[package]
name = "kv_store_async"
version = "0.1.0"
edition = "2021"

[dependencies]
omnipaxos = { path = "../../omnipaxos", features = ["macros", "tokio_runtime"] }
omnipaxos_storage = { path = "../../omnipaxos_storage" }
tokio = { version = "1", features = ["rt-multi-thread", "sync", "time", "macros"] }
serde = { version = "1.0", features = ["derive"] }
