[package]
name = "omnipaxos_macros"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
syn = "1.0"
quote = "1.0"

[dev-dependencies]
omnipaxos_core = { path = "../omnipaxos_core", features = ["macros"] }
omnipaxos_storage = { path = "../omnipaxos_storage" }